### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by newhouse**
## Description of the change

`yarn version`

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development
- [x] No previous tests unrelated to the changed code fail in development

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ] At least one reviewer has been requested
- [ ] Changes have been reviewed by at least one other engineer
- [ ] The relevant project board has been selected in Projects to auto-link to this pull request

### CODE REVIEW

**Comment by newhouse** [comment]
Also @benogle can you or @ralbayaty invite/add me to our Org on `npm.js`? Username is `newhouse`...but the e-mail is my personal one.

**Comment by benogle** [comment]
You have been invited

**Comment by newhouse** [comment]
Thanks @benogle I'm in!. If you think this looks good, plz approve and I will merge and publish on npm

**Comment by ralbayaty** [comment]
So looks like I forgot to `yarn publish` in master to get a v2.0.0 package release after merging the last PR I did in here. Because of this the changelog in here seems to squash out the v2.0.0. Suppose it isn't the end of the world.

**Comment by ralbayaty** [comment]
> Are the changes still in the repo @ralbayaty ? I'm not a fan of this version autocreate thing...

Yeah looks like it only squashed the versions together in the changelog but the commits are still in there.

The changelog autocreate stuff was a swift thing I put in to help devs see what has changed without adding any overhead to us.

`yarn version` is meant to be run inline during a `yarn publish` (or `npm publish`, I forget which one we use here) off of master, and not in a PR directly. So basically in master branch we `yarn publish` which bumps the version, updates the changelog, then pushes the package to the registry. 
 
> If they're in there, I may just go along with things how they are...nbd.

I think we should do this all off master and nix this PR. If things don't work as planned we can change the flow to whatever you think is easier from a dev standpoint and document it better (this should have already been done to avoid confusion).

**Comment by newhouse** [comment]
> I think we should do this all off master and nix this PR. If things don't work as intended we can change the flow to whatever you think is easier from a dev standpoint and document it better (this should have already been done to avoid confusion).

I tried to do it off of master, but could not. Git(hub) complained when pushing that a reviewer needed to approve it, or that I can't push straight to master or something...

**Comment by ralbayaty** [comment]
> I tried to do it off of master, but could not. Git(hub) complained when pushing that a reviewer needed to approve it, or that I can't push straight to master or something...

No bueno. In that case, go ahead with whatever gets your stuff in and feel free to change whatever you need to make this easiest. It would be great to have a low/no maintenance CHANGELOG, but if not currently feasible we can nix it for time being.

**Pull request merged**
